name: lite_oneapi
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  logging: ^1.2.0
  json_annotation: ^4.9.0
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.9.2
  lints: ^5.0.0
  test: ^1.24.0
